# Generated by Django 5.1.1 on 2024-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Curso')),
                ('slug', models.SlugField(verbose_name='Categoria')),
                ('short_description', models.TextField(verbose_name='Descrição')),
                ('long_description', models.TextField(verbose_name='Sobre o curso')),
                ('pdf', models.FileField(upload_to='', verbose_name='Material')),
                ('video_aula', models.URLField(verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
