# Generated by Django 5.1.1 on 2024-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL do vídeo')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do vídeo')),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='video_aula',
        ),
        migrations.AddField(
            model_name='curso',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursos.video'),
        ),
    ]
