# Generated by Django 5.1.1 on 2024-12-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_video_remove_curso_video_aula_curso_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='Material')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do')),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='curso',
            name='aluno',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='curso',
            name='arquivos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursos.material'),
        ),
    ]
