# Generated by Django 5.1.1 on 2024-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_material_remove_curso_pdf_alter_curso_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(upload_to='materiais/', verbose_name='Material'),
        ),
    ]
