# Generated by Django 5.1.1 on 2024-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_material_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(upload_to='', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do arquivo'),
        ),
    ]
