# Generated by Django 5.1.4 on 2024-12-11 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_material_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='aluno',
        ),
        migrations.AddField(
            model_name='curso',
            name='aluno',
            field=models.ManyToManyField(default=True, related_name='cursos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
