# Generated by Django 5.1.4 on 2024-12-11 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_remove_curso_aluno_curso_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='aluno',
            field=models.ManyToManyField(blank=True, related_name='cursos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
