# Generated by Django 4.2.16 on 2024-12-26 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0010_alter_curso_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='cursos.curso')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='cursos.video')),
            ],
            options={
                'unique_together': {('aluno', 'curso', 'video')},
            },
        ),
    ]
